language: node_js
node_js:
  - 10.16.3

install:
  - npm install

script: npm run build
after_script:
  - cd ./dist
  - git init
  - git add -A
  - git commit -m 'deploy'
  - git push -f git@github.com:yaochi930229/mi-mall.git master:gh-pages
branches:
  only:
    - master